# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  setup:
    # The type of runner that the job will run on
    name: Install configu CLI upsert, eval and upload cache
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - name: Install configu CLI and update to a specific version
        run: |
          curl https://cli.configu.com/install.sh | sh
          configu update --version 0.16.0-next.8

      - name: upsert
        run: configu run --script upsert

      - name: eval
        run: configu run --script eval

      - name: Upload cache
        uses: actions/upload-artifact@v4
        with:
          name: store_cache
          path: cache.db

  eval:
    name: Evaluate cache
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3

      - name: Download cache
        uses: actions/download-artifact@v4
        with:
          name: store_cache

      - name: upsert
        run: configu run --script upsert2

      - name: eval
        run: configu run --script eval2


